apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /mnt/some-new/directory/structure
    type: DirectoryOrCreate


---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi



# PV and PVC are mounted using the storageClassName
